// src/services/epocaService.ts
import { supabase } from "../supabaseClient";
import type { Epoca, EpocaRow } from "../models/Epoca";

/** DB -> App */
function rowToEpoca(r: any): Epoca {
  return {
    id: r.id,
    name: r.name ?? "",
    activa: r.activa ?? false,
  };
}

/** App -> DB */
function epocaToRow(e: Epoca): EpocaRow {
  return {
    id: e.id,
    name: e.name ?? "",
    activa: e.activa ?? false,
  };
}

/**
 * List all épocas
 */
export async function listEpocas(): Promise<Epoca[]> {
  const { data, error } = await supabase
    .from("epoca")
    .select("*")
    .order("id", { ascending: true });

  if (error) {
    console.error("Error fetching épocas:", error);
    throw error;
  }
  
  console.log("Raw data from epoca table:", data);
  console.log("Number of records:", data?.length ?? 0);
  
  if (!data || data.length === 0) {
    console.warn("No épocas found in database");
    return [];
  }
  
  const result = data.map(rowToEpoca);
  console.log("Mapped épocas:", result);
  return result;
}

/**
 * Get a single época by id
 */
export async function getEpocaById(id: number): Promise<Epoca | null> {
  const { data, error } = await supabase
    .from("epoca")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error) throw error;
  return data ? rowToEpoca(data) : null;
}

/**
 * Get the active época (where activa = true)
 */
export async function getActiveEpoca(): Promise<Epoca | null> {
  const { data, error } = await supabase
    .from("epoca")
    .select("*")
    .eq("activa", true)
    .maybeSingle();

  if (error) throw error;
  return data ? rowToEpoca(data) : null;
}

/**
 * Create a new época
 */
export async function createEpoca(epoca: Omit<Epoca, "id">): Promise<Epoca> {
  const row = epocaToRow({ ...epoca, id: 0 }); // id will be generated by DB
  delete (row as any).id;

  const { data, error } = await supabase
    .from("epoca")
    .insert(row)
    .select("*")
    .single();

  if (error) throw error;
  return rowToEpoca(data);
}

/**
 * Update an existing época
 */
export async function updateEpoca(epoca: Epoca): Promise<Epoca> {
  const row = epocaToRow(epoca);

  const { data, error } = await supabase
    .from("epoca")
    .update({ name: row.name, activa: row.activa })
    .eq("id", row.id)
    .select("*")
    .single();

  if (error) throw error;
  return rowToEpoca(data);
}

/**
 * Set an época as active and deactivate all others
 */
export async function setActiveEpoca(id: number): Promise<void> {
  // First, deactivate all épocas
  const { error: deactivateError } = await supabase
    .from("epoca")
    .update({ activa: false });

  if (deactivateError) throw deactivateError;

  // Then, activate the selected época
  const { error: activateError } = await supabase
    .from("epoca")
    .update({ activa: true })
    .eq("id", id);

  if (activateError) throw activateError;
}

/**
 * Create or update an época (upsert)
 */
export async function upsertEpoca(epoca: Epoca): Promise<Epoca> {
  if (epoca.id && epoca.id > 0) {
    return updateEpoca(epoca);
  } else {
    return createEpoca(epoca);
  }
}

/**
 * Delete an época by id
 */
export async function deleteEpoca(id: number): Promise<void> {
  const { error } = await supabase.from("epoca").delete().eq("id", id);
  if (error) throw error;
}

